/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.edigonzales;

import java.io.IOException;
import java.net.MalformedURLException;

public class App {

    public static void main(String[] args) throws MalformedURLException, IOException {
        
        FlatGeobufReader fgbReader = new FlatGeobufReader();
        fgbReader.makeItSo();
        
    }
}
